<a href="https://colab.research.google.com/github/anshmehta337/deep-learning/blob/main/linearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [54]:
X_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

In [55]:
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(b)
print(W)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [56]:
#linear regression equation looks like y=wx+b

In [57]:
y=W*X_train+b

In [58]:
y

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [59]:
cost = torch.mean((y - y_train) ** 2)

In [60]:
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [61]:
op=optim.SGD([W,b],lr=0.01)

In [62]:
epochs=1111
for e in range(epochs+1):
    hypothesis = X_train * W + b


    cost = torch.mean((hypothesis - y_train) ** 2)

    op.zero_grad()
    cost.backward()
    op.step()


    if e % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            e, e, W.item(), b.item(), cost.item()
        ))

Epoch    0/0 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/100 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/200 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/300 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/400 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/500 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/600 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/700 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/800 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/900 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158
Epoch 1100/1100 W: 0.989, b: 0.026 Cost: 0.000098


In [63]:
RESS = y_train* W + b
print(RESS)

tensor([[1.0142],
        [2.0030],
        [2.9919]], grad_fn=<AddBackward0>)


In [64]:
class linear(nn.Module):
  def __init__(self):
    super().__init__()
    self.Linear=nn.Linear(1,1)
  def forward(self,x):
    return self.Linear(x)

In [65]:
model = linear()

In [66]:
hypothesi = model(X_train)
print(hypothesi)

tensor([[1.2239],
        [1.9882],
        [2.7525]], grad_fn=<AddmmBackward0>)


In [69]:
import torch
import torch.nn as nn
import torch.optim as optim

# Training data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[1.0], [2.0], [3.0]])


class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)


num_epochs = 2000


for epoch in range(num_epochs):

    hypothesis = model(x_train)

    loss = criterion(hypothesis, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [100/2000], Loss: 0.0456
Epoch [200/2000], Loss: 0.0282
Epoch [300/2000], Loss: 0.0174
Epoch [400/2000], Loss: 0.0108
Epoch [500/2000], Loss: 0.0067
Epoch [600/2000], Loss: 0.0041
Epoch [700/2000], Loss: 0.0025
Epoch [800/2000], Loss: 0.0016
Epoch [900/2000], Loss: 0.0010
Epoch [1000/2000], Loss: 0.0006
Epoch [1100/2000], Loss: 0.0004
Epoch [1200/2000], Loss: 0.0002
Epoch [1300/2000], Loss: 0.0001
Epoch [1400/2000], Loss: 0.0001
Epoch [1500/2000], Loss: 0.0001
Epoch [1600/2000], Loss: 0.0000
Epoch [1700/2000], Loss: 0.0000
Epoch [1800/2000], Loss: 0.0000
Epoch [1900/2000], Loss: 0.0000
Epoch [2000/2000], Loss: 0.0000


In [70]:
print(model(y_train))

tensor([[1.0033],
        [2.0007],
        [2.9981]], grad_fn=<AddmmBackward0>)
